[tools]
python = "3.13.14"
rust = "nightly"
git-cliff = "latest"
cargo-release = "latest"
"cargo:licet" = "0.2.1"

[tools.'pipx:reuse']
version = "latest"
uvx_args = "--python 3.13"
extras = "charset-normalizer"

[settings]
experimental = true
