//! SPDX expression parsing, canonicalization, and semantic comparison (FR-005),
//! plus the embedded license-text corpus lookup (FR-017, FR-028).

// Generated by build.rs: BUNDLED_LICENSES and SPDX_LIST_VERSION.
include!(concat!(env!("OUT_DIR"), "/licet_licenses.rs"));

/// Version of the embedded SPDX license-list snapshot (FR-028).
pub fn spdx_list_version() -> &'static str {
    SPDX_LIST_VERSION
}

/// SPDX identifiers whose full text is embedded in the binary.
pub fn bundled_ids() -> Vec<&'static str> {
    BUNDLED_LICENSES.iter().map(|(id, _)| *id).collect()
}

/// Full license text for a bundled identifier, if present.
pub fn bundled_text(id: &str) -> Option<&'static str> {
    BUNDLED_LICENSES
        .iter()
        .find(|(k, _)| k.eq_ignore_ascii_case(id))
        .map(|(_, text)| *text)
}

/// True when `id` is a `LicenseRef-*` custom identifier (REUSE/SPDX custom refs).
pub fn is_license_ref(id: &str) -> bool {
    id.starts_with("LicenseRef-")
}

/// True when `id` is a recognized SPDX license id (or a `LicenseRef-*`).
pub fn is_known_id(id: &str) -> bool {
    if is_license_ref(id) {
        return true;
    }
    spdx::license_id(id).is_some()
}

/// Validate a full SPDX expression (allowing `LicenseRef-*` and `+`/`WITH`).
///
/// Strict dependency parsing only: sloppy-but-guessable input (`mit`,
/// `apache2`) is rejected here and diagnosed downstream. Case tolerance lives
/// in comparison ([`expressions_equal`]), not acceptance.
/// Returns `Ok(())` for a parseable expression, otherwise an explanatory message.
pub fn validate_expression(expr: &str) -> Result<(), String> {
    let trimmed = expr.trim();
    if trimmed.is_empty() {
        return Err("empty license expression".to_string());
    }
    spdx::Expression::parse(trimmed)
        .map(|_| ())
        .map_err(|e| format!("invalid SPDX expression `{trimmed}`: {e}"))
}

/// Parse an expression and render it in a canonical, comparable form.
///
/// Canonical form is equal up to commutativity, associativity, whitespace,
/// parenthesization, and case of identifiers (FR-005). Full distributive
/// equivalence is an explicit non-goal for v1.
pub fn parse_canonical(expr: &str) -> Result<String, String> {
    let trimmed = expr.trim();
    if trimmed.is_empty() {
        return Err("empty license expression".to_string());
    }
    parse_expression_ast(trimmed)
        .map(|parts| parts.join(" "))
        .ok_or_else(|| format!("invalid SPDX expression `{trimmed}`"))
}

/// Every license/exception identifier an expression references, in first-seen
/// order: parsed from the dependency AST via requirement spans (so tabs,
/// newlines, and casing variants split correctly), falling back to
/// whitespace splitting for invalid expressions.
pub fn expression_ids(expr: &str) -> Vec<String> {
    if let Ok(parsed) = ::spdx::Expression::parse(expr) {
        return ids_from_spans(expr, &parsed);
    }
    let folded = casefold_known_ids(expr);
    if folded != expr
        && let Ok(parsed) = ::spdx::Expression::parse(&folded)
    {
        return ids_from_spans(&folded, &parsed);
    }
    fallback_split_ids(expr)
}

/// Read identifiers out of a parsed expression: each requirement span names
/// the license exactly as written (`MIT`, `GPL-2.0+`, `LicenseRef-X`), while
/// a `WITH` exception travels in the requirement's `addition` (the iterator
/// does not yield it separately, so spans alone would drop it).
fn ids_from_spans(source: &str, parsed: &::spdx::Expression) -> Vec<String> {
    let mut ids = Vec::new();
    let mut push = |id: &str| {
        let id = id.trim().trim_end_matches('+');
        if !id.is_empty() && !ids.contains(&id.to_string()) {
            ids.push(id.to_string());
        }
    };
    for req in parsed.requirements() {
        let text = &source[req.span.start as usize..req.span.end as usize];
        push(text);
        if let Some(addition) = &req.req.addition {
            push(&addition.to_string());
        }
    }
    ids
}

/// Best-effort identifier split for expressions that do not parse.
fn fallback_split_ids(expr: &str) -> Vec<String> {
    let mut ids = Vec::new();
    for token in expr.split(|c: char| c.is_whitespace() || c == '(' || c == ')') {
        let id = token.trim().trim_end_matches('+');
        if id.is_empty()
            || id.eq_ignore_ascii_case("or")
            || id.eq_ignore_ascii_case("and")
            || id.eq_ignore_ascii_case("with")
        {
            continue;
        }
        if !ids.contains(&id.to_string()) {
            ids.push(id.to_string());
        }
    }
    ids
}

/// Semantic equality of two SPDX expressions via canonical form (FR-005, F12).
pub fn expressions_equal(a: &str, b: &str) -> bool {
    match (parse_expression_ast(a), parse_expression_ast(b)) {
        (Some(x), Some(y)) => x == y,
        // Preserve raw-string behavior for values the parser rejects: equal only
        // when byte-identical after trimming (callers only invoke this on
        // validated expressions, so this is unreachable in practice).
        _ => a.trim() == b.trim(),
    }
}

/// Parse an expression into canonical sorted-operand form through the dependency
/// AST ([`spdx::Expression::iter`], postfix `Req`/`Op` nodes), so `MIT OR
/// Apache-2.0` and `(Apache-2.0 OR MIT)` compare equal (FR-005, F12). The postfix
/// nodes rebuild a tree on a stack, so grouping comes from the parser — `AND`
/// binds tighter than `OR`, `WITH` binds tightest, and `AND`/`OR`/`WITH` are
/// never confused by string surgery.
///
/// Strict parsing first; on failure a whole-token case-fold retry supplies the
/// promised standard-id case tolerance (`mit` → `MIT`, `apache-2.0` →
/// `Apache-2.0`) without the dependency's lax prefix/slash/deprecated
/// guessing. Anything still unparseable is `None` and the callers preserve
/// exact-string behavior for it.
fn parse_expression_ast(expression: &str) -> Option<Vec<String>> {
    parse_ast_strict(expression).or_else(|| parse_ast_strict(&casefold_known_ids(expression)))
}

/// Lowercase → canonical spelling for every known license/exception id,
/// built once from the dependency's own tables.
fn canonical_id_map() -> &'static std::collections::HashMap<String, &'static str> {
    static MAP: std::sync::OnceLock<std::collections::HashMap<String, &'static str>> =
        std::sync::OnceLock::new();
    MAP.get_or_init(|| {
        let mut map = std::collections::HashMap::new();
        for lic in spdx::identifiers::LICENSES {
            map.entry(lic.name.to_ascii_lowercase()).or_insert(lic.name);
        }
        for exc in spdx::identifiers::EXCEPTIONS {
            map.entry(exc.name.to_ascii_lowercase()).or_insert(exc.name);
        }
        map
    })
}

/// True for characters inside an SPDX id token. Operators, parens, `+`, and
/// whitespace split tokens; `/` stays inside so slash-expressions reach the
/// strict parser verbatim (and stay rejected there).
fn is_id_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '/')
}

/// Rewrite whole-token known ids to canonical spelling (`apache-2.0` →
/// `Apache-2.0`). Only exact (modulo case) full-token hits change, so prose,
/// operators, `LicenseRef-*`, and sloppy prefixes (`apache2`) pass through
/// untouched for the strict parser to judge.
fn casefold_known_ids(expression: &str) -> String {
    let map = canonical_id_map();
    let mut out = String::with_capacity(expression.len());
    let mut token = String::new();
    for c in expression.chars() {
        if is_id_char(c) {
            token.push(c);
            continue;
        }
        flush_token(&mut token, &mut out, map);
        out.push(c);
    }
    flush_token(&mut token, &mut out, map);
    out
}

fn flush_token(
    token: &mut String,
    out: &mut String,
    map: &std::collections::HashMap<String, &'static str>,
) {
    if token.is_empty() {
        return;
    }
    match map.get(&token.to_ascii_lowercase()) {
        Some(canonical) => out.push_str(canonical),
        None => out.push_str(token),
    }
    token.clear();
}

/// Strict-parse one expression string into canonical sorted-operand form.
fn parse_ast_strict(expression: &str) -> Option<Vec<String>> {
    let parsed = spdx::Expression::parse(expression).ok()?;
    // Rebuild the tree from postfix nodes; same-operator runs flatten so
    // associativity (`A AND (B AND C)` ≡ `(A AND B) AND C`) holds structurally.
    #[derive(Debug)]
    enum Ast {
        Req(String),
        And(Vec<Ast>),
        Or(Vec<Ast>),
    }
    fn push_op(stack: &mut Vec<Ast>, is_or: bool) {
        let right = stack.pop();
        let left = stack.pop();
        match (left, right) {
            (Some(l), Some(r)) => {
                let mut children = Vec::with_capacity(2);
                for child in [l, r] {
                    match (is_or, child) {
                        (true, Ast::Or(nested)) | (false, Ast::And(nested)) => {
                            children.extend(nested);
                        }
                        (_, other) => children.push(other),
                    }
                }
                stack.push(if is_or {
                    Ast::Or(children)
                } else {
                    Ast::And(children)
                });
            }
            // Unbalanced input cannot come from the parser; keep the survivor.
            (Some(l), None) => stack.push(l),
            (None, Some(r)) => stack.push(r),
            (None, None) => {}
        }
    }
    let mut stack: Vec<Ast> = Vec::new();
    for node in parsed.iter() {
        match node {
            spdx::expression::ExprNode::Req(req) => {
                stack.push(Ast::Req(requirement_text(&req.req)));
            }
            spdx::expression::ExprNode::Op(spdx::expression::Operator::Or) => {
                push_op(&mut stack, true);
            }
            spdx::expression::ExprNode::Op(spdx::expression::Operator::And) => {
                push_op(&mut stack, false);
            }
        }
    }
    if stack.len() != 1 {
        return None;
    }
    fn render(node: &Ast, out: &mut Vec<String>) {
        match node {
            Ast::Req(text) => out.push(text.clone()),
            Ast::Or(children) => {
                let mut parts: Vec<String> = children
                    .iter()
                    .map(|c| {
                        let mut sub = Vec::new();
                        render(c, &mut sub);
                        sub.join(" ")
                    })
                    .collect();
                parts.sort();
                out.extend(parts);
                out.push("OR".to_string());
            }
            Ast::And(children) => {
                let mut parts: Vec<String> = children
                    .iter()
                    .map(|c| {
                        let mut sub = Vec::new();
                        render(c, &mut sub);
                        sub.join(" ")
                    })
                    .collect();
                parts.sort();
                out.extend(parts);
                out.push("AND".to_string());
            }
        }
    }
    let mut out = Vec::new();
    render(&stack[0], &mut out);
    Some(out)
}

/// Canonical text of one license requirement: canonical id spelling plus any
/// `WITH` exception. `LicenseRef-*` values round-trip through the same parser.
fn requirement_text(req: &spdx::LicenseReq) -> String {
    let mut s = req.license.to_string();
    if let Some(addition) = &req.addition {
        s.push_str(&format!(" WITH {addition}"));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn commutative_or_is_equal() {
        assert!(expressions_equal("MIT OR Apache-2.0", "Apache-2.0 OR MIT"));
    }

    #[test]
    fn with_exception_yields_both_ids() {
        assert_eq!(
            expression_ids("GPL-2.0-only WITH Classpath-exception-2.0"),
            vec![
                "GPL-2.0-only".to_string(),
                "Classpath-exception-2.0".to_string()
            ]
        );
        assert_eq!(
            expression_ids("MIT\tor\tApache-2.0"),
            vec!["MIT".to_string(), "Apache-2.0".to_string()]
        );
    }

    #[test]
    fn commutative_and_is_equal() {
        // Policy AND-combinations compare order-insensitively.
        assert!(expressions_equal(
            "MIT AND Apache-2.0",
            "Apache-2.0 AND MIT"
        ));
    }

    #[test]
    fn whitespace_and_parens_normalized() {
        assert!(expressions_equal(
            "MIT OR Apache-2.0",
            "(MIT  OR   Apache-2.0)"
        ));
    }

    #[test]
    fn case_insensitive_ids() {
        assert!(expressions_equal("mit", "MIT"));
    }

    #[test]
    fn plus_operator_distinct() {
        assert!(!expressions_equal("GPL-2.0-only", "GPL-2.0-or-later"));
    }

    #[test]
    fn with_exception_roundtrip() {
        assert!(expressions_equal(
            "Apache-2.0 WITH LLVM-exception",
            "Apache-2.0 WITH LLVM-exception"
        ));
    }

    #[test]
    fn nested_associativity() {
        assert!(expressions_equal(
            "MIT AND (Apache-2.0 AND ISC)",
            "(ISC AND MIT) AND Apache-2.0"
        ));
    }

    #[test]
    fn license_ref_known() {
        assert!(is_known_id("LicenseRef-MarqueLicense-1.0"));
        assert!(validate_expression("LicenseRef-MarqueLicense-1.0").is_ok());
    }

    #[test]
    fn bundled_lookup_works() {
        assert!(bundled_text("MIT").is_some());
        assert!(bundled_ids().contains(&"Apache-2.0"));
    }

    #[test]
    fn invalid_expression_rejected() {
        assert!(validate_expression("Not A Real License").is_err());
    }

    #[test]
    fn compound_parens_both_orders() {
        assert!(expressions_equal(
            "MIT AND (Apache-2.0 OR ISC)",
            "(ISC OR Apache-2.0) AND MIT"
        ));
        assert!(expressions_equal(
            "(MIT OR Apache-2.0)",
            "Apache-2.0 OR (MIT)"
        ));
    }

    #[test]
    fn operators_never_confused() {
        assert!(!expressions_equal(
            "MIT OR Apache-2.0",
            "MIT AND Apache-2.0"
        ));
        // Precedence is structural: `A AND B OR C` is `(A AND B) OR C`.
        assert!(expressions_equal(
            "MIT AND Apache-2.0 OR ISC",
            "(MIT AND Apache-2.0) OR ISC"
        ));
        assert!(!expressions_equal(
            "MIT AND Apache-2.0 OR ISC",
            "MIT AND (Apache-2.0 OR ISC)"
        ));
    }

    #[test]
    fn tab_newline_separators() {
        assert!(expressions_equal(
            "MIT\tOR\nApache-2.0",
            "MIT OR Apache-2.0"
        ));
    }

    #[test]
    fn mixed_case_ids_equal() {
        assert!(expressions_equal("MIT or apache-2.0", "Apache-2.0 OR MIT"));
        assert!(expressions_equal(
            "mit and apache-2.0",
            "Apache-2.0 AND MIT"
        ));
        assert!(expressions_equal(
            "MIT WITH Classpath-exception-2.0",
            "mit with classpath-exception-2.0"
        ));
    }

    #[test]
    fn licenseref_compound_sorts() {
        assert!(expressions_equal(
            "LicenseRef-Acme-1.0 OR MIT",
            "MIT OR LicenseRef-Acme-1.0"
        ));
    }

    #[test]
    fn unparseable_falls_back_to_exact() {
        assert!(expressions_equal("Not A License", "Not A License"));
        assert!(!expressions_equal("Not A License", "not a license"));
        assert!(!expressions_equal("MIT", "Not A License"));
    }
}
