//! SPDX expression parsing, canonicalization, and semantic comparison (FR-005),
//! plus the embedded license-text corpus lookup (FR-017, FR-028).

// Generated by build.rs: BUNDLED_LICENSES and SPDX_LIST_VERSION.
include!(concat!(env!("OUT_DIR"), "/licet_licenses.rs"));

/// Version of the embedded SPDX license-list snapshot (FR-028).
pub fn spdx_list_version() -> &'static str {
    SPDX_LIST_VERSION
}

/// SPDX identifiers whose full text is embedded in the binary.
pub fn bundled_ids() -> Vec<&'static str> {
    BUNDLED_LICENSES.iter().map(|(id, _)| *id).collect()
}

/// Full license text for a bundled identifier, if present.
pub fn bundled_text(id: &str) -> Option<&'static str> {
    BUNDLED_LICENSES
        .iter()
        .find(|(k, _)| k.eq_ignore_ascii_case(id))
        .map(|(_, text)| *text)
}

/// True when `id` is a `LicenseRef-*` custom identifier (REUSE/SPDX custom refs).
pub fn is_license_ref(id: &str) -> bool {
    id.starts_with("LicenseRef-")
}

/// True when `id` is a recognized SPDX license id (or a `LicenseRef-*`).
pub fn is_known_id(id: &str) -> bool {
    if is_license_ref(id) {
        return true;
    }
    spdx::license_id(id).is_some()
}

/// Validate a full SPDX expression (allowing `LicenseRef-*` and `+`/`WITH`).
///
/// Returns `Ok(())` for a parseable expression, otherwise an explanatory message.
pub fn validate_expression(expr: &str) -> Result<(), String> {
    parse_canonical(expr).map(|_| ())
}

/// Parse an expression and render it in a canonical, comparable form.
///
/// Canonical form is equal up to commutativity, associativity, whitespace,
/// parenthesization, and case of identifiers (FR-005, research §2). Full
/// distributive equivalence is an explicit non-goal for v1.
pub fn parse_canonical(expr: &str) -> Result<String, String> {
    let trimmed = expr.trim();
    if trimmed.is_empty() {
        return Err("empty license expression".to_string());
    }

    // `spdx::Expression` accepts LicenseRef-* and compound expressions, and validates
    // identifiers against the bundled SPDX list.
    let parsed = spdx::Expression::parse(trimmed)
        .map_err(|e| format!("invalid SPDX expression `{trimmed}`: {e}"))?;

    Ok(canonicalize(&parsed))
}

/// Semantic equality of two SPDX expressions via canonical form (FR-005).
pub fn expressions_equal(a: &str, b: &str) -> bool {
    match (parse_canonical(a), parse_canonical(b)) {
        (Ok(ca), Ok(cb)) => ca == cb,
        // Fall back to case-insensitive string compare for unparseable inputs so two
        // identical raw strings still compare equal.
        _ => a.trim().eq_ignore_ascii_case(b.trim()),
    }
}

/// Render an `spdx::Expression` into a canonical string, flattening associative AND/OR
/// nestings and sorting commutative operands so equivalent expressions render identically.
fn canonicalize(expr: &spdx::Expression) -> String {
    normalize_boolean(expr.as_ref())
}

/// Boolean AST used purely for canonicalization (associativity + commutativity).
enum Node {
    Or(Vec<Node>),
    And(Vec<Node>),
    Leaf(String),
}

/// Normalize a (possibly parenthesized) AND/OR expression string into canonical form.
fn normalize_boolean(s: &str) -> String {
    render(&parse_node(s))
}

fn parse_node(s: &str) -> Node {
    let s = strip_outer_parens(s.trim());
    let ors = split_top_level(s, "OR");
    if ors.len() > 1 {
        return Node::Or(ors.iter().map(|x| parse_node(x)).collect());
    }
    let ands = split_top_level(s, "AND");
    if ands.len() > 1 {
        return Node::And(ands.iter().map(|x| parse_node(x)).collect());
    }
    Node::Leaf(normalize_leaf(s))
}

/// Flatten same-operator children into a single operand list.
fn flatten<'a>(node: &'a Node, want_or: bool, out: &mut Vec<&'a Node>) {
    match node {
        Node::Or(children) if want_or => children.iter().for_each(|c| flatten(c, true, out)),
        Node::And(children) if !want_or => children.iter().for_each(|c| flatten(c, false, out)),
        other => out.push(other),
    }
}

fn render(node: &Node) -> String {
    match node {
        Node::Leaf(s) => s.clone(),
        Node::Or(_) => {
            let mut operands = Vec::new();
            flatten(node, true, &mut operands);
            // OR is lowest precedence; AND children need no parens, leaves none.
            let mut parts: Vec<String> = operands.iter().map(|c| render(c)).collect();
            parts.sort();
            parts.dedup();
            parts.join(" OR ")
        }
        Node::And(_) => {
            let mut operands = Vec::new();
            flatten(node, false, &mut operands);
            // AND binds tighter than OR; wrap any OR child in parens.
            let mut parts: Vec<String> = operands
                .iter()
                .map(|c| match c {
                    Node::Or(_) => format!("({})", render(c)),
                    _ => render(c),
                })
                .collect();
            parts.sort();
            parts.dedup();
            parts.join(" AND ")
        }
    }
}

/// Split a string on a top-level (non-parenthesized) ` OP ` boundary.
fn split_top_level(s: &str, op: &str) -> Vec<String> {
    let s = strip_outer_parens(s.trim());
    let bytes = s.as_bytes();
    let mut depth = 0i32;
    let mut parts = Vec::new();
    let mut start = 0usize;
    let needle = format!(" {op} ");
    let mut i = 0usize;
    while i < bytes.len() {
        match bytes[i] {
            b'(' => depth += 1,
            b')' => depth -= 1,
            _ => {}
        }
        if depth == 0 && s[i..].to_ascii_uppercase().starts_with(&needle) {
            parts.push(s[start..i].to_string());
            i += needle.len();
            start = i;
            continue;
        }
        i += 1;
    }
    parts.push(s[start..].to_string());
    parts
}

/// Remove one layer of fully-enclosing parentheses, if present.
fn strip_outer_parens(s: &str) -> &str {
    let t = s.trim();
    if t.starts_with('(') && t.ends_with(')') {
        // Verify the first `(` matches the last `)`.
        let inner = &t[1..t.len() - 1];
        let mut depth = 0i32;
        for (idx, c) in inner.char_indices() {
            match c {
                '(' => depth += 1,
                ')' => {
                    depth -= 1;
                    if depth < 0 {
                        return t; // unbalanced — keep as-is
                    }
                }
                _ => {}
            }
            let _ = idx;
        }
        if depth == 0 {
            return inner.trim();
        }
    }
    t
}

/// Normalize a single leaf token: trim, recurse into parens, canonicalize id case and `+`,
/// and preserve `WITH` exceptions.
fn normalize_leaf(s: &str) -> String {
    let t = strip_outer_parens(s.trim());
    if t.is_empty() {
        return String::new();
    }
    // Recurse if the leaf still contains top-level operators (was parenthesized).
    if split_top_level(t, "OR").len() > 1 || split_top_level(t, "AND").len() > 1 {
        return format!("({})", normalize_boolean(t));
    }
    // Handle `ID WITH Exception`.
    if let Some((lic, exc)) = split_with(t) {
        return format!("{} WITH {}", canon_id(&lic), exc.trim());
    }
    canon_id(t)
}

/// Split `A WITH B` at the top level, if present.
fn split_with(s: &str) -> Option<(String, String)> {
    let parts = split_top_level(s, "WITH");
    if parts.len() == 2 {
        Some((parts[0].clone(), parts[1].clone()))
    } else {
        None
    }
}

/// Canonicalize a bare license identifier: map to the official SPDX casing when known,
/// preserve a trailing `+`, and keep `LicenseRef-*` verbatim.
fn canon_id(id: &str) -> String {
    let id = id.trim();
    let (base, plus) = match id.strip_suffix('+') {
        Some(b) => (b, "+"),
        None => (id, ""),
    };
    if is_license_ref(base) {
        return format!("{base}{plus}");
    }
    match spdx::license_id(base) {
        Some(found) => format!("{}{plus}", found.name),
        None => format!("{base}{plus}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn commutative_or_is_equal() {
        assert!(expressions_equal("MIT OR Apache-2.0", "Apache-2.0 OR MIT"));
    }

    #[test]
    fn whitespace_and_parens_normalized() {
        assert!(expressions_equal(
            "MIT OR Apache-2.0",
            "(MIT  OR   Apache-2.0)"
        ));
    }

    #[test]
    fn case_insensitive_ids() {
        assert!(expressions_equal("mit", "MIT"));
    }

    #[test]
    fn plus_operator_distinct() {
        assert!(!expressions_equal("GPL-2.0-only", "GPL-2.0-or-later"));
    }

    #[test]
    fn with_exception_roundtrip() {
        assert!(expressions_equal(
            "Apache-2.0 WITH LLVM-exception",
            "Apache-2.0 WITH LLVM-exception"
        ));
    }

    #[test]
    fn nested_associativity() {
        assert!(expressions_equal(
            "MIT AND (Apache-2.0 AND ISC)",
            "(ISC AND MIT) AND Apache-2.0"
        ));
    }

    #[test]
    fn license_ref_known() {
        assert!(is_known_id("LicenseRef-MarqueLicense-1.0"));
        assert!(validate_expression("LicenseRef-MarqueLicense-1.0").is_ok());
    }

    #[test]
    fn bundled_lookup_works() {
        assert!(bundled_text("MIT").is_some());
        assert!(bundled_ids().contains(&"Apache-2.0"));
    }

    #[test]
    fn invalid_expression_rejected() {
        assert!(validate_expression("Not A Real License").is_err());
    }
}
