//! `init` / `bootstrap` — derive a config from current repository state (FR-018; US5).
//!
//! Inspects existing headers and `REUSE.toml`/`.reuse/dep5`, then emits a `license.toml`
//! whose projection reproduces current licensing — generalizing per-file observations into
//! extension/glob rules where possible (SC-008). Modifies no source files.

use std::collections::BTreeMap;
use std::path::PathBuf;

use super::{Format, InitArgs};
use crate::config::LicensingConfiguration;
use crate::detect;
use crate::error::{ExitCode, Result};
use crate::reuse::oob::OutOfBand;
use crate::walk::{self, Selection, discover_root};

pub fn run(args: InitArgs) -> Result<ExitCode> {
    let cwd = std::env::current_dir()?;
    let root = discover_root(&cwd);
    let oob = OutOfBand::load(&root);

    // Observe each file's detected license, keyed by extension.
    let discovered = walk::enumerate(&root, &Selection::FullTree, &[])?;
    let mut by_ext: BTreeMap<String, BTreeMap<String, usize>> = BTreeMap::new();
    let mut license_counts: BTreeMap<String, usize> = BTreeMap::new();

    for d in &discovered {
        if d.excluded {
            continue;
        }
        let head = detect::read_head(&d.abs_path).unwrap_or_default();
        let sidecar = detect::read_sidecar(&d.abs_path);
        let actual = detect::detect(&d.rel_path, &head, sidecar.as_deref(), &oob);
        let lic = match actual.detected_license {
            Some(l) => l,
            None => continue,
        };
        *license_counts.entry(lic.clone()).or_default() += 1;
        if let Some(ext) = d.rel_path.extension().and_then(|e| e.to_str()) {
            *by_ext
                .entry(ext.to_string())
                .or_default()
                .entry(lic)
                .or_default() += 1;
        }
    }

    // Most common license overall becomes the default.
    let default_license = license_counts
        .iter()
        .max_by_key(|(_, n)| **n)
        .map(|(l, _)| l.clone());

    // For each extension with a single dominant license differing from the default,
    // emit an `ext` rule (prefers ext/glob over per-file rules — SC-008).
    let mut rules: Vec<(String, String)> = Vec::new();
    for (ext, licenses) in &by_ext {
        if let Some((lic, _)) = licenses.iter().max_by_key(|(_, n)| **n)
            && Some(lic) != default_license.as_ref()
        {
            rules.push((ext.clone(), lic.clone()));
        }
    }

    let toml = render_config(default_license.as_deref(), &rules);

    // Validate the generated config parses (projection sanity).
    LicensingConfiguration::from_toml(&toml)?;

    let out_path = args
        .output
        .clone()
        .unwrap_or_else(|| PathBuf::from("license.toml"));
    std::fs::write(&out_path, &toml)?;

    match args.format {
        Format::Json => println!(
            "{{\"generated\":\"{}\",\"rules\":{},\"from_reuse\":{}}}",
            out_path.display(),
            rules.len(),
            args.from_reuse
        ),
        Format::Human => {
            eprintln!(
                "Wrote {} ({} rule(s) inferred).",
                out_path.display(),
                rules.len()
            );
            print!("{toml}");
        }
    }
    Ok(ExitCode::Success)
}

fn render_config(default: Option<&str>, rules: &[(String, String)]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by `licet init` from existing repository state.\n\n");
    if let Some(d) = default {
        out.push_str("[default]\n");
        out.push_str(&format!("license = \"{d}\"\n\n"));
    }
    for (ext, lic) in rules {
        out.push_str("[[rule]]\n");
        out.push_str(&format!("ext = \"{ext}\"\n"));
        out.push_str(&format!("license = \"{lic}\"\n\n"));
    }
    out
}
